### ISSUE TITLE
STRY: Frequent Drinks Section

### ISSUE THREAD

**Issue by petarilievCS** [petarilievCS/Caffeine-Tracker#22]
**Tasks:**
- [x] Add a relation in CoreData between a ConsumedDrink and Drink
- [x] Implement method in DatabaseManager that returns the top 5 most consumed drinks (by frequency) 
- [ ] Add section in UITableView in Drinks Tab
